### ISSUE TITLE
Make a !vote or !suggest command

### ISSUE THREAD

**Issue by Isabwella** [momentum-mod/discord-bot#1]
Would be interesting to have a command for the bot to make polls, possibly only team members can create the polls. The poll would be in a separate #polls channel with a #polls-discussion channel to discuss the suggestions. Something along the lines of:

_*!poll "Add the ability to disable other people's rockets in spectator mode" 75*_

The 75 would represent the percentage of votes needed for the vote to be "accepted" or deemed important.
The bot would then post that message into the #polls channel, and then the bot would put a thumbs up and down reaction on the comment, and people can then vote based on that.

**Comment by hexaflexahexagon** [comment]
other bots do this exact thing and better, no reason to implement. we haven't needed to run a poll like this in ages anyways.
