### ISSUE TITLE
YouTube Streams

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/discord-bot#120]
Basically the same as the Twitch setup but using YouTube's API. I have absolutely no experience with YouTube API stuff so you'll have to read up on it yourself.

**Comment by Gocnak** [comment]
I did an initial investigation into this and it's not really possible to get streams by game. Idk why, but YouTube doesn't seem to want to invest into this API so this issue is blocked until then. You could filter by Livestreams that have "momentum" in the title but... That's really broad.

**Comment by tsa96** [comment]
Oh for God's sake, forgot about that. Maybe not worth it in that case, given how few people stream on YouTube anyway.

**Comment by tsa96** [comment]
We discussed a bit ago and I forgot to close this. The API is shit, can't filter by game, so pretty impossible for us to work with
