### ISSUE TITLE
Reaction-based roles should check all users who have/haven't reacted on startup

### ISSUE THREAD

**Issue by Hona** [momentum-mod/discord-bot#27]
If users add/remove a reaction while the bot is down,, it won't give/take the role. On startup, it should check all users, and update roles to be correct.

This is probably a long running action with ~3600 users to check.

**Comment by Gocnak** [comment]
Shouldn't check against *all* users, only the users that reacted vs the users with the role.

**Comment by Hona** [comment]
What happens when a user removes a reaction while the bot is down?

**Comment by Gocnak** [comment]
They keep the role (bot wasn't online to remove it right?), and the bot compares who reacted to who has the role, finds the set difference, and removes the role from those who don't have the reaction.

**Comment by Hona** [comment]
Yep, this will work.
