### ISSUE TITLE
(Admin) Log deleted messages into private channel

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/discord-bot#39]
Discord doesn't seem to do a good job of logging user actions on it's own, it would be nice to have a log for deleted / edited messages for the case of someone posting something in violation of the rules and quickly deleting it (E.G spamming pings).  If possible, display the original message, the poster and the user who deleted it. 

Currently it seems to me that the audit log only shows that a deletion occurred if it's removed by a moderator and not the poster. It also does not show what the message was. There are other logging bots around that could be used but this would be nice to have integrated.

**Comment by Hona** [comment]
Ok I'm thinking of a config option for #message-history channel, and all delete/editted messages go in there.
