### ISSUE TITLE
Make discord bot react with a key when people ask for a key

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/discord-bot#4]
"Hey can I get a key?" "Where do I get a key?" etc, automatically reacts to them with a key emoji, to give them a key :)

**Comment by patrickmoc** [comment]
This should also respond with an explanation of why they will not be getting a key. Something like 

> We have detected that you are asking for a key to get access to the game. The game is currently in a private alpha and keys at this point are being reserved for specific users that are contributing to the development of the mod through code, assets or mapping. 1.0 will be the mod's public beta. Check #faq-and-rules for more information

This could also be activated by !key or a command similar if it is not set off automatically for a user.

**Comment by Flipybitz** [comment]
> This should also respond with an explanation of why they will not be getting a key. Something like
> 
> > We have detected that you are asking for a key to get access to the game. The game is currently in a private alpha and keys at this point are being reserved for specific users that are contributing to the development of the mod through code, assets or mapping. 1.0 will be the mod's public beta. Check #faq-and-rules for more information
> 
> This could also be activated by !key or a command similar if it is not set off automatically for a user.

I like this idea also, my suggestion was mostly for fun but doing a !key command could be equally as useful

**Comment by Hona** [comment]
Right now I'm thinking on checking messages for 'I get a key', in that exact order. When it finds that then:

1. React with the key
2. Send a message similar to what patrickmoc suggested above

**Comment by patrickmoc** [comment]
There is also commonly people asking how to download the game / get the game. Maybe that would be a good thing to trigger it as well since its basically the same answer. With that said making it too sensitive might make it come up for unrelated things.

**Comment by Hona** [comment]
This is a good idea too. Limiting the bot to react to unranked users might be good too. (Join the server just to ask for a key/download the game)
