### ISSUE TITLE
Add !key message cooldown

### ISSUE THREAD

**Issue by izzydesigns** [momentum-mod/discord-bot#57]
I know Hona is thinking about making it a 5 minute cool down for each user, but I think it's a bit silly to make it per-user since this would mean if two people come into #general and for whatever reason both ask for a key within like 30 seconds of each other, the bot's message would already be there for them to read, no need to send it again ykno?

My suggestion is a per-channel 5 minute cooldown instead. This way if one user in #general-momentum asks and another in #general, that it'd still send a message in each channel but have the 5 minutes of cooldown before being sent again in that same channel. I think this would be a more balanced approach.

**Comment by Hona** [comment]
My only concern with this is people will read chat history

**Comment by izzydesigns** [comment]
Sure, but if someone in #general-momentum asks for a key, the person in say #general-bhop won't see that message, so therefore making it per-channel would make sense. Unles you're pointing out a different issue?

**Comment by Hona** [comment]
An alternative to this would be letting momentum team members react with an X or something to remove the bots message

**Comment by izzydesigns** [comment]
> An alternative to this would be letting momentum team members react with an X or something to remove the bots message

Oh team members can already remove any chat messages, so that wouldn't really be necessary. But yeah you're right it's not too big of a deal. You can close this if you'd like

**Comment by Hona** [comment]
Yep, and since this will be removed when 1.0.0 comes out, no need to worry about it too much.
