### ISSUE TITLE
Ratelimit reaction based roles

### ISSUE THREAD

**Issue by Hona** [momentum-mod/discord-bot#72]
Needs to log a warning that the user is spamming the reaction.

Add a config option for max actions per 1/2/5? minute period, then when an action is added increase a users counter. Once the limit is hit, ignore the users requests for a timeout period (config option) and log it. 

A simple way to clear this data would be a job every 2*period minutes to wipe the cache where the last request was > period ago.

**Comment by Gocnak** [comment]
Superceded by needing to do #148
