### ISSUE TITLE
Create a trust system for new users

### ISSUE THREAD

**Issue by Hona** [momentum-mod/discord-bot#78]
Something like 10+ messages and 3+ days before being able to send media

**Comment by Gocnak** [comment]
And do not give them the role if they have a "blacklist" role already -- the "send media" part comes from getting the "trusted" role, but we also have an "untrustworthy" role that would be given to potentially problematic people that should never be "trusted".

**Comment by Hona** [comment]
Completion Checklist:

- [ ] On every message received, store the message count for each day, user, channel - maybe MySQL or Postgres
- [ ] After incrementing the user count, if they don't have the 'Trusted' or the 'Blacklist' role, and if they have been in the server for 3+ days, SUM the total messages for the user. If its > 10, give them the role.
- [ ] Add a command for making a user 'Blacklist'ed

This solution should also allow for analytics of user activity, without storing all messages (don't want to store messages for sake of privacy).
