### ISSUE TITLE
Add map wr tracker

### ISSUE THREAD

**Issue by ghost** [momentum-mod/discord-bot#92]
I had an idea to make the bot ping a role (filter by gamemode maybe?) and send a wr embed including the map name, player username, time, and a link to the map download.

**Comment by Hona** [comment]
Things like WR notifications, and commands to interact with the game API is planned - [see here](https://github.com/momentum-mod/discord-bot/projects/1) for a stub. It will be made when the website allows for third party authentication with the API.
