### ISSUE TITLE
Readme has broken website image

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/discord-bot#98]
https://github.com/momentum-mod/discord-bot/blob/net-core/README.md
![image](https://user-images.githubusercontent.com/62961532/130500446-a37e349a-f9d7-488c-8ccf-3d3159d64ce2.png)

See https://github.com/momentum-mod/website/commit/a9f200b1ba0c895a6cd2ddbd15077978206b8592 for the change that probably broke it

**Comment by xKaelyn** [comment]
@hexaflexahexagon Fixed | awaiting pull request approval.
